In [33]:
import pandas as pd
print("libraries is imported")

libraries is imported

In [34]:
import pandas as pd

df=pd.read_csv('student_performance.csv')

print("dataframe is created")

dataframe is created

In [35]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [36]:
df.head(10)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023

In [37]:
df.shape

(30, 13)

In [38]:
df.shape[0]

30

In [39]:
df.shape[1]

13

In [40]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [41]:
print(df.columns.tolist())

['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [42]:
print(df.dtypes)

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [43]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [44]:
df.isnull()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False

In [45]:
import numpy as np

null_indices = np.random.choice(df.index, 5, replace=False)

df.loc[null_indices, 'math_score'] = np.nan

In [46]:
print(df['math_score'].isnull().sum())

5

In [47]:
df['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [48]:
df['gender'].value_counts()

gender
Male      15
Female    15
Name: count, dtype: int64

In [49]:
df['city'].unique()

array(['Mumbai', 'Ahmedabad', 'Delhi', 'Hyderabad', 'Kochi', 'Pune',
       'Bangalore', 'Lucknow', 'Varanasi', 'Kolkata', 'Chennai', 'Jaipur',
       'Mysore', 'Thrissur', 'Bhopal', 'Agra', 'Patna', 'Nagpur',
       'Dehradun', 'Chandigarh', 'Thiruvananthapuram', 'Surat',
       'Allahabad', 'Kanpur', 'Indore'], dtype=object)

In [50]:
df['city'].value_counts()

city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [51]:
df['department'].value_counts()

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [52]:
student=df['city']

In [53]:
students = df[df['city'].isin(['Chennai', 'Mumbai'])]   #instead of .isin can use ==
print(students[['name', 'city', 'programming_score']])

            name     city  programming_score
0   Aarav Sharma   Mumbai                 91
10   Vikram Iyer  Chennai                 72

In [54]:
df['total_score'] = df['math_score']+df['science_score']+df['english_score']+df['programming_score']
lowstd=df.loc[df['total_score'].idxmin()]
print(lowstd)

student_id                       1017
name                     Manoj Pandey
age                                21
gender                           Male
department                      Civil
semester                            2
math_score                       56.0
science_score                      61
english_score                      55
programming_score                  38
attendance_percentage              65
city                            Patna
admission_year                   2023
total_score                     210.0
Name: 16, dtype: object

In [55]:
#student-data-explorer

### 1. Dataset Overview

In [56]:
# Total number of students
total_students = df.shape[0]
print(f"Total number of students: {total_students}")

# Total number of columns
total_columns = df.shape[1]
print(f"Total number of columns: {total_columns}")

# Number of unique departments
unique_departments = df['department'].nunique()
print(f"Number of unique departments: {unique_departments}")

Total number of students: 30
Total number of columns: 14
Number of unique departments: 4

### 2. Department Wise Analysis

In [57]:
department_counts = df['department'].value_counts()
print("Count of students in each department:")
print(department_counts)

Count of students in each department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

### 3. Score Analysis

In [58]:
# Highest math score
highest_math = df['math_score'].max()
print(f"Highest math score: {highest_math}")

# Lowest math score
lowest_math = df['math_score'].min()
print(f"Lowest math score: {lowest_math}")

# Average math score
avg_math = df['math_score'].mean()
print(f"Average math score: {avg_math:.2f}")

# Average programming score
avg_programming = df['programming_score'].mean()
print(f"Average programming score: {avg_programming:.2f}")

# Average attendance percentage
avg_attendance = df['attendance_percentage'].mean()
print(f"Average attendance percentage: {avg_attendance:.2f}%")

Highest math score: 95.0
Lowest math score: 56.0
Average math score: 75.56
Average programming score: 67.60
Average attendance percentage: 84.50%

### 4. Gender Wise Analysis

In [59]:
avg_total_score_by_gender = df.groupby('gender')['total_score'].mean()
print("Average total score by gender:")
print(avg_total_score_by_gender)

Average total score by gender:
gender
Female    303.153846
Male      282.583333
Name: total_score, dtype: float64

### 5. Top Performers

In [60]:
top_5_students = df.sort_values(by='total_score', ascending=False).head(5)
print("Top 5 students based on total score:")
print(top_5_students[['name', 'department', 'total_score']])

Top 5 students based on total score:
           name        department  total_score
9    Ananya Das  Computer Science        371.0
21  Tanvi Mehta  Computer Science        367.0
7   Divya Singh  Computer Science        356.0
4    Arjun Nair  Computer Science        356.0
12   Suresh Rao  Computer Science        334.0

### 6. Attendance Analysis

In [61]:
low_attendance_students = df[df['attendance_percentage'] < 75]

if not low_attendance_students.empty:
    print("Students with attendance below 75%:")
    print(low_attendance_students[['name', 'department', 'attendance_percentage']])
else:
    print("All students have attendance above 75%.")

Students with attendance below 75%:
             name   department  attendance_percentage
5     Meera Joshi  Electronics                     72
8    Rahul Mishra   Mechanical                     68
16   Manoj Pandey        Civil                     65
20  Harish Pillai  Electronics                     74
22   Sanjay Dubey        Civil                     70
27  Sunita Pillai        Civil                     73

###1.How many students are from the Electronics Department?

In [62]:
electronics_count = len(df[df["department"] == "ECE"])
print("Students from Electronics Department :", electronics_count)

Students from Electronics Department : 0

###2.What is the average attendance of female students?

In [63]:
female_attendance = df[df["gender"] == "Female"]["attendance_percentage"].mean()

print("Average attendance of female students :", female_attendance)

Average attendance of female students : 88.53333333333333

###3. Who is the student with the lowest programming score?

In [64]:
lowest_programming = df.loc[df["programming_score"].idxmin()]

print("Student with lowest programming score :", lowest_programming["name"])

Student with lowest programming score : Manoj Pandey

###4. How many students scored above 80 in math?

In [65]:
above_80_math = len(df[df["math_score"] > 80])

print("Students scored above 80 in math :", above_80_math)

Students scored above 80 in math : 8

###5. What is the average total_score for students with attendance above 90%?

In [66]:
avg_total_above_90 = df[df["attendance_percentage"] > 90]["total_score"].mean()

print("Average total score :", avg_total_above_90)

Average total score : 329.0